/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostel.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author HP
 */
public class Hostel extends javax.swing.JPanel {

    /**
     * Creates new form Hostel
     */
    public Hostel() {
        initComponents();
        setRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        room = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        reset = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD NEW HOSTEL TO RECORD");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("HOSTEL NAME");
        jLabel2.setMaximumSize(new java.awt.Dimension(170, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(170, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("HOSTEL ADDRESS");
        jLabel3.setMaximumSize(new java.awt.Dimension(170, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(170, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("LAND-LORD MOBILE");
        jLabel4.setMaximumSize(new java.awt.Dimension(170, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(170, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("HOSTEL PRICE");
        jLabel5.setMaximumSize(new java.awt.Dimension(170, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(170, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("HOSTEL DESCRIPTION");
        jLabel6.setMaximumSize(new java.awt.Dimension(170, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(170, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(170, 25));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("NO. OF ROOMS");
        jLabel7.setMaximumSize(new java.awt.Dimension(170, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(170, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(170, 25));

        name.setMaximumSize(new java.awt.Dimension(150, 25));
        name.setMinimumSize(new java.awt.Dimension(150, 25));
        name.setPreferredSize(new java.awt.Dimension(150, 25));

        address.setMaximumSize(new java.awt.Dimension(150, 25));
        address.setMinimumSize(new java.awt.Dimension(150, 25));
        address.setPreferredSize(new java.awt.Dimension(150, 25));

        mobile.setMaximumSize(new java.awt.Dimension(150, 25));
        mobile.setMinimumSize(new java.awt.Dimension(150, 25));
        mobile.setPreferredSize(new java.awt.Dimension(150, 25));

        price.setMaximumSize(new java.awt.Dimension(150, 25));
        price.setMinimumSize(new java.awt.Dimension(150, 25));
        price.setPreferredSize(new java.awt.Dimension(150, 25));

        room.setMaximumSize(new java.awt.Dimension(150, 25));
        room.setMinimumSize(new java.awt.Dimension(150, 25));
        room.setPreferredSize(new java.awt.Dimension(150, 25));

        desc.setMaximumSize(new java.awt.Dimension(150, 25));
        desc.setMinimumSize(new java.awt.Dimension(150, 25));
        desc.setPreferredSize(new java.awt.Dimension(150, 25));

        reset.setBackground(new java.awt.Color(255, 204, 153));
        reset.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 0));
        reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reset.setText("RESET");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        reset.setMaximumSize(new java.awt.Dimension(100, 25));
        reset.setMinimumSize(new java.awt.Dimension(100, 25));
        reset.setOpaque(true);
        reset.setPreferredSize(new java.awt.Dimension(100, 25));
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hostel.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Hostel.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Hostel.this.mouseExited(evt);
            }
        });

        add.setBackground(new java.awt.Color(255, 204, 153));
        add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 0));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setText("ADD RECORD");
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        add.setMaximumSize(new java.awt.Dimension(100, 25));
        add.setMinimumSize(new java.awt.Dimension(100, 25));
        add.setOpaque(true);
        add.setPreferredSize(new java.awt.Dimension(100, 25));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hostel.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Hostel.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Hostel.this.mouseExited(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTERED HOSTEL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 51, 0))); // NOI18N

        container.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 51, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("S/N");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel10.setMaximumSize(new java.awt.Dimension(50, 25));
        jLabel10.setMinimumSize(new java.awt.Dimension(50, 25));
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel10, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 51, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("HOSTEL ID");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel18.setMaximumSize(new java.awt.Dimension(100, 25));
        jLabel18.setMinimumSize(new java.awt.Dimension(100, 25));
        jLabel18.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel18, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 51, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("HOSTEL NAME");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel19.setMaximumSize(new java.awt.Dimension(180, 25));
        jLabel19.setMinimumSize(new java.awt.Dimension(180, 25));
        jLabel19.setPreferredSize(new java.awt.Dimension(180, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel19, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 51, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LOCATION");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel13.setMaximumSize(new java.awt.Dimension(180, 25));
        jLabel13.setMinimumSize(new java.awt.Dimension(180, 25));
        jLabel13.setPreferredSize(new java.awt.Dimension(180, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 51, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PRICE");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel14.setMaximumSize(new java.awt.Dimension(100, 25));
        jLabel14.setMinimumSize(new java.awt.Dimension(100, 25));
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 51, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("NO OF ROOM");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel15.setMaximumSize(new java.awt.Dimension(100, 25));
        jLabel15.setMinimumSize(new java.awt.Dimension(100, 25));
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel15, gridBagConstraints);

        jScrollPane1.setViewportView(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEntered
        // TODO add your handling code here:
        evt.getComponent().setBackground(new Color(204,51,0));
    }//GEN-LAST:event_mouseEntered

    private void mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExited
        // TODO add your handling code here:
        evt.getComponent().setBackground(new Color(255,204,153));
    }//GEN-LAST:event_mouseExited

    private String getId(int a)
    {
        if(a <10)
         {
             return "00"+a;
         }
         else if(a <100)
         {
             return "0"+a;
         }
         else
             return ""+a;
    }
    
    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        // TODO add your handling code here:
        if(evt.getSource() == add)
        {
            if(!name.getText().equals(""))
            {
            
                if(!room.getText().equals(""))
                {
                    if(!price.getText().equals(""))
                    {
                        if(!(address.getText().equals("") || mobile.getText().equals("") || desc.getText().equals("")))
                        {
                            try {
                                //add details to db
                                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel", "root", "");
                                st = con.createStatement();
                                
                                rs = st.executeQuery("SELECT count(*) FROM hostel");
                                rs.next();
                                int a = rs.getInt(1) + 1;
                                
                                ps = con.prepareStatement("INSERT INTO hostel VALUES(?,?,?,?,?,?,?)");
                                
                                ps.setString(1, "HST" + getId(a));
                                ps.setString(2, name.getText());
                                ps.setString(3, address.getText());
                                ps.setString(4, price.getText());
                                ps.setString(5, desc.getText());
                                ps.setString(6, mobile.getText());
                                ps.setString(7, room.getText());
                                
                                int b = ps.executeUpdate();
                                int c = Integer.parseInt(room.getText());
                                ps = con.prepareStatement("INSERT INTO rooms VALUES(?,?,?)");
                                
                                for(int i=1; i<=c; i++)
                                {
                                    ps.setString(1, "RMN"+getId(a) + getId(i));
                                    ps.setString(2, "HST" + getId(a));
                                    ps.setString(3, "available");
                                    ps.executeUpdate();
                                }
                                
                                if(b != -1)
                                {
                                    JOptionPane.showMessageDialog(this, "Hostel succesfully added");
                                    name.setText("");
                                    address.setText("");
                                    mobile.setText("");
                                    price.setText("");
                                    desc.setText("");
                                    room.setText("");
                                    //refresh registered hostel panel
                                    setRecord();
                                }
                                else
                                    JOptionPane.showMessageDialog(this, "Problem Adding Hostel Try again..");
                                
                            } catch (SQLException ex) {
                                Logger.getLogger(Hostel.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            
                        }
                        else
                            //all fields must be fill
                            JOptionPane.showMessageDialog(this, "all fields must be fill");
                    }
                    else
                        //enter a valid price for the hostel rooms
                        JOptionPane.showMessageDialog(this,"");
                }
                else
                    //enter the nuo of rooms available in the hostel
                    JOptionPane.showMessageDialog(this,"enter the nuo of rooms available in the hostel");
            }
            else
                //enter a valid hostel name
                JOptionPane.showMessageDialog(this,"enter a valid hostel name");
        }
        else if(evt.getSource() == reset)
        {
            name.setText("");
            address.setText("");
            mobile.setText("");
            price.setText("");
            desc.setText("");
            room.setText("");
        }
    }//GEN-LAST:event_mouseClicked

    private void setRecord()
    {
        try {
            cont = new GridBagConstraints();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM hostel");
            
            int i=1;
            container.removeAll();
            setTitle();
            
            while(rs.next())
            {
                JLabel sn = new JLabel("" + i);
                sn.setPreferredSize(new Dimension(50,25));
                sn.setHorizontalAlignment(SwingConstants.CENTER);
                sn.setForeground(Color.red);
                sn.setFont(new Font("Dialog", Font.BOLD, 12));
                addComp(sn, 0, i);
                
                JLabel std = new JLabel(rs.getString(1));
                std.setHorizontalAlignment(SwingConstants.CENTER);
                std.setForeground(Color.BLACK);
                std.setFont(new Font("Dialog", Font.BOLD, 12));
                addComp(std, 1,i);
                
                JLabel rmn = new JLabel(rs.getString(2));
                rmn.setHorizontalAlignment(SwingConstants.CENTER);
                rmn.setForeground(Color.BLACK);
                rmn.setFont(new Font("Dialog", Font.BOLD, 12));
                addComp(rmn, 2,i);
                
                JLabel in = new JLabel(rs.getString(3));
                in.setHorizontalAlignment(SwingConstants.CENTER);
                in.setForeground(Color.BLACK);
                in.setFont(new Font("Dialog", Font.BOLD, 12));
                addComp(in, 3,i);
                
                JLabel out = new JLabel(rs.getString(4));
                out.setHorizontalAlignment(SwingConstants.CENTER);
                out.setForeground(Color.BLACK);
                out.setFont(new Font("Dialog", Font.BOLD, 12));
                addComp(out, 4,i);
                
                JLabel drop = new JLabel(rs.getString(7));
                drop.setHorizontalAlignment(SwingConstants.CENTER);
                drop.setForeground(Color.BLACK);
                drop.setFont(new Font("Dialog", Font.BOLD, 12));
                addComp(drop, 5, i++);
            }
            container.repaint();
            container.revalidate();
            container.validate();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    private void addComp(JComponent comp, int x, int y)
    {
        cont.anchor = GridBagConstraints.PAGE_START;
        cont.fill = GridBagConstraints.BOTH;
        cont.gridheight = 1;
        cont.gridwidth = 1;
        cont.gridx = x;
        cont.gridy = y;
        
        comp.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        container.add(comp, cont);
    }
    private void setTitle()
    {
        JLabel sn = new JLabel("S/N");
        sn.setPreferredSize(new Dimension(50,25));
        sn.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        sn.setFont(new Font("Dialog", Font.BOLD, 12));
        sn.setForeground(new Color(204,51,0));
        sn.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(sn, 0,0);
        
        JLabel std = new JLabel("HOSTEL ID");
        std.setPreferredSize(new Dimension(120,25));
        std.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        std.setFont(new Font("Dialog", Font.BOLD, 12));
        std.setForeground(new Color(204,51,0));
        std.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(std, 1,0);
        
        JLabel rm = new JLabel("HOSTEL NAME");
        rm.setPreferredSize(new Dimension(180,25));
        rm.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        rm.setFont(new Font("Dialog", Font.BOLD, 12));
        rm.setForeground(new Color(204,51,0));
        rm.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(rm , 2,0);
        
        JLabel in = new JLabel("LOCATION");
        in.setPreferredSize(new Dimension(180,25));
        in.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        in.setFont(new Font("Dialog", Font.BOLD, 12));
        in.setForeground(new Color(204,51,0));
        in.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(in, 3,0);
        
        JLabel out = new JLabel("PRICE");
        out.setPreferredSize(new Dimension(100,25));
        out.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        out.setFont(new Font("Dialog", Font.BOLD, 12));
        out.setForeground(new Color(204,51,0));
        out.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(out, 4, 0);
        
        JLabel drop = new JLabel("NO OF ROOM");
        drop.setPreferredSize(new Dimension(100,25));
        drop.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        drop.setFont(new Font("Dialog", Font.BOLD, 12));
        drop.setForeground(new Color(204,51,0));
        drop.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(drop, 5, 0);
    }
    
    private GridBagConstraints cont;
    private Connection con;
    private Statement st;
    private PreparedStatement ps;
    private ResultSet rs;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JTextField address;
    private javax.swing.JPanel container;
    private javax.swing.JTextField desc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JLabel reset;
    private javax.swing.JTextField room;
    // End of variables declaration//GEN-END:variables
}
