package hostel.management.system;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
       
        calendar = new GregorianCalendar();
	 try{
        initComponents();
        
        this.calendarNav();
        this.setCalendar();
        this.setTitle();
        this.setDisplay();
        Image im = getToolkit().createImage(getClass().getResource("admin.jpg"));
        im = im.getScaledInstance(120, 120, Image.SCALE_SMOOTH);
        this.pix.setIcon(new ImageIcon(im));
        setLocationRelativeTo(null);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pix = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        hostel1 = new javax.swing.JLabel();
        student1 = new javax.swing.JLabel();
        room1 = new javax.swing.JLabel();
        record1 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        student = new javax.swing.JLabel();
        record = new javax.swing.JLabel();
        room = new javax.swing.JLabel();
        hostel = new javax.swing.JLabel();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOSTEL MANAGEMENT SYSTEM");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        setForeground(new java.awt.Color(255, 153, 0));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1000, 720));
        setMinimumSize(new java.awt.Dimension(1000, 720));
        setResizable(false);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/logo.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        pix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/admin.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hostel Manager");

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 2, true), "Navigation Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 153, 51))); // NOI18N

        hostel1.setBackground(new java.awt.Color(255, 255, 204));
        hostel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        hostel1.setForeground(new java.awt.Color(204, 0, 0));
        hostel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hostel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/addstudent.png"))); // NOI18N
        hostel1.setText("ADD HOSTEL");
        hostel1.setIconTextGap(8);
        hostel1.setMaximumSize(new java.awt.Dimension(30, 25));
        hostel1.setMinimumSize(new java.awt.Dimension(30, 25));
        hostel1.setPreferredSize(new java.awt.Dimension(30, 25));
        hostel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntered1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExited1(evt);
            }
        });

        student1.setBackground(new java.awt.Color(255, 255, 204));
        student1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        student1.setForeground(new java.awt.Color(204, 0, 0));
        student1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        student1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/addstudent.png"))); // NOI18N
        student1.setText("ADD STUDENT");
        student1.setIconTextGap(8);
        student1.setMaximumSize(new java.awt.Dimension(30, 25));
        student1.setMinimumSize(new java.awt.Dimension(30, 25));
        student1.setPreferredSize(new java.awt.Dimension(30, 25));
        student1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntered1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExited1(evt);
            }
        });

        room1.setBackground(new java.awt.Color(255, 255, 204));
        room1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        room1.setForeground(new java.awt.Color(204, 0, 0));
        room1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        room1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/addroom.png"))); // NOI18N
        room1.setText("ALLOT ROOM");
        room1.setIconTextGap(8);
        room1.setMaximumSize(new java.awt.Dimension(30, 25));
        room1.setMinimumSize(new java.awt.Dimension(30, 25));
        room1.setPreferredSize(new java.awt.Dimension(30, 25));
        room1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntered1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExited1(evt);
            }
        });

        record1.setBackground(new java.awt.Color(255, 255, 204));
        record1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        record1.setForeground(new java.awt.Color(204, 0, 0));
        record1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        record1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/search.png"))); // NOI18N
        record1.setText("VIEW RECORD");
        record1.setIconTextGap(8);
        record1.setMaximumSize(new java.awt.Dimension(30, 25));
        record1.setMinimumSize(new java.awt.Dimension(30, 25));
        record1.setPreferredSize(new java.awt.Dimension(30, 25));
        record1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntered1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExited1(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 255, 204));
        logout.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(204, 0, 0));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout.setText("LOG OUT");
        logout.setIconTextGap(8);
        logout.setMaximumSize(new java.awt.Dimension(30, 25));
        logout.setMinimumSize(new java.awt.Dimension(30, 25));
        logout.setPreferredSize(new java.awt.Dimension(30, 25));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntered1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExited1(evt);
            }
        });

        about.setBackground(new java.awt.Color(255, 255, 204));
        about.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        about.setForeground(new java.awt.Color(204, 0, 0));
        about.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        about.setText("ABOUT");
        about.setIconTextGap(8);
        about.setMaximumSize(new java.awt.Dimension(30, 25));
        about.setMinimumSize(new java.awt.Dimension(30, 25));
        about.setPreferredSize(new java.awt.Dimension(30, 25));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseEntered1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseExited1(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hostel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(student1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(room1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(record1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addComponent(about, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(student1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hostel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(room1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(record1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(about, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pix, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(pix, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 50));

        home.setBackground(new java.awt.Color(255, 255, 204));
        home.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/home.png"))); // NOI18N
        home.setText("HOME");
        home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        home.setIconTextGap(5);
        home.setOpaque(true);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main.this.mouseExited(evt);
            }
        });

        student.setBackground(new java.awt.Color(255, 255, 204));
        student.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        student.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/addstudent.png"))); // NOI18N
        student.setText("ADD STUDENT");
        student.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        student.setIconTextGap(5);
        student.setOpaque(true);
        student.setPreferredSize(new java.awt.Dimension(82, 26));
        student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main.this.mouseExited(evt);
            }
        });

        record.setBackground(new java.awt.Color(255, 255, 204));
        record.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        record.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/search.png"))); // NOI18N
        record.setText("VIEW RECORD");
        record.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        record.setIconTextGap(5);
        record.setOpaque(true);
        record.setPreferredSize(new java.awt.Dimension(83, 26));
        record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main.this.mouseExited(evt);
            }
        });

        room.setBackground(new java.awt.Color(255, 255, 204));
        room.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        room.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        room.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/addroom.png"))); // NOI18N
        room.setText("ALLOT ROOM");
        room.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        room.setIconTextGap(5);
        room.setOpaque(true);
        room.setPreferredSize(new java.awt.Dimension(82, 26));
        room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main.this.mouseExited(evt);
            }
        });

        hostel.setBackground(new java.awt.Color(255, 255, 204));
        hostel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        hostel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/addstudent.png"))); // NOI18N
        hostel.setText("ADD HOSTEL");
        hostel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        hostel.setIconTextGap(5);
        hostel.setOpaque(true);
        hostel.setPreferredSize(new java.awt.Dimension(82, 26));
        hostel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main.this.mouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Main.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Main.this.mouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(student, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hostel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(record, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hostel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(logo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setDisplay()
    {
        new Thread(){
            @Override
            public void run()
            {
                container.removeAll();
                container.repaint();
                container.revalidate();
                
                JLabel image = new JLabel();
                container.add(image);
                Random rand = new Random();
                while(true)
                {
                 
                    Image im = getToolkit().createImage(getClass().getResource(images[rand.nextInt(3)]+""));
                    im = im.getScaledInstance(740, 520, Image.SCALE_SMOOTH);
                    image.setIcon(new ImageIcon(im));
                    image.revalidate();
                    image.repaint();
                    image.validate();
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            
        }.start();
    }
    private void mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEntered
        evt.getComponent().setBackground(new Color(255,153,0));
        evt.getComponent().setForeground(Color.BLUE);
    }//GEN-LAST:event_mouseEntered

    private void mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExited
        evt.getComponent().setBackground(new Color(255,255,204));
        evt.getComponent().setForeground(Color.BLACK);
    }//GEN-LAST:event_mouseExited

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        // TODO add your handling code here:
        if(evt.getSource() == home)
        {
            setDisplay();
        }
        else if(evt.getSource() == record || evt.getSource() == record1)
        {
            container.removeAll();
            container.add( new Record());
            container.revalidate();
            container.repaint();
            container.validate();
        }
        else if(evt.getSource() == student || evt.getSource() == student1)
        {
            container.removeAll();
            container.add( new Student());
            container.revalidate();
            container.repaint();
            container.validate();
        }
        else if(evt.getSource() == logout)
        {
            Main.super.dispose();
            new Login(null, true).setVisible(true);
        }
        else if(evt.getSource() == about)
        {
            container.removeAll();
            container.add( new About());
            container.revalidate();
            container.repaint();
            container.validate();
        }
        else if(evt.getSource() == hostel || evt.getSource() == hostel1)
        {
        container.removeAll();
        container.add( new Hostel());
        container.revalidate();
        container.repaint();
        container.validate();
        }
        else if(evt.getSource() == room || evt.getSource() == room1)
        {
        container.removeAll();
        container.add( new Room());
        container.revalidate();
        container.repaint();
        container.validate();
        }
            
    }//GEN-LAST:event_mouseClicked

    private void mouseEntered1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEntered1
        // TODO add your handling code here:
        evt.getComponent().setForeground(Color.BLUE);
    }//GEN-LAST:event_mouseEntered1

    private void mouseExited1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExited1
        // TODO add your handling code here:
        evt.getComponent().setForeground(new Color(204,0,0));
    }//GEN-LAST:event_mouseExited1

    private void calendarNav()
	{
		right = new JButton(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/r.PNG")));
		right.setContentAreaFilled(false);
		right.setBorder(null);
		right.setBounds(185,0,30,30);
		right.addActionListener((ActionEvent ae) -> {
                    calendar.set(Calendar.MONTH, (calendar.get(Calendar.MONTH) + 1));
                    setCalendar();
                });
		jPanel3.add(right);
		
		left = new JButton(new javax.swing.ImageIcon(getClass().getResource("/hostel/management/system/l.PNG")));
		left.setContentAreaFilled(false);
		left.setBorder(null);
		left.setBounds(0,0,30,30);
		left.addActionListener((ActionEvent ae) -> {
                    calendar.set(Calendar.MONTH, (calendar.get(Calendar.MONTH) - 1));
                    setCalendar();
                });
		jPanel3.add(left);
	}
	private void setTitle()
	{
		monthYear = new JLabel();
		monthYear.setHorizontalAlignment(SwingConstants.CENTER);
		monthYear.setForeground(Color.BLUE);
		monthYear.setFont(new Font(null, Font.BOLD, 18));
		monthYear.setBounds(30,0,155,30);
		jPanel3.add(monthYear);
		
		int x = 0;
		daysOfWeek = new JLabel[7];
		
		for(int i=0; i< 7; i++)
		{
			daysOfWeek[i] = new JLabel();
			daysOfWeek[i].setText(dayWeek[i]);
			daysOfWeek[i].setForeground(Color.blue);
			daysOfWeek[i].setHorizontalAlignment(SwingConstants.CENTER);
			daysOfWeek[i].setFont(new Font(null, Font.BOLD, 12));
			daysOfWeek[i].setBounds(x,30,30,30);
			x += 31;
			jPanel3.add(daysOfWeek[i]);
		}
		
	}

        private void setCalendar()
	{
		jPanel3.removeAll();
		setTitle();
		calendarNav();
		int month =  calendar.getActualMaximum(Calendar.DAY_OF_MONTH);
		int currentDay = calendar.get(Calendar.DAY_OF_MONTH);
		int year = calendar.get(Calendar.YEAR);
		int months = calendar.get(Calendar.MONTH) + 1;
		
		calendar.add(Calendar.DAY_OF_MONTH, -(currentDay -  1));
		int day = calendar.get(Calendar.DAY_OF_WEEK);
		calendar.add(Calendar.DAY_OF_MONTH, +(currentDay - 1));
		
		monthYear.setText(monthOfYear[months-1] + " " + year);
		
		days = new JLabel[month];
		
		int x = 10;
		int y = 60;
		int j;
		for(int i=1; i< (month + day); i++)
		{
			if(i < day)
			{
				x += 31;
			}
			else
			{	
				j = (i-day);
				days[j] = new JLabel();
				days[j].setText("" + ( (j + 1)));
				days[j].setBounds(x,y,30,30);
				days[j].setHorizontalAlignment(SwingConstants.CENTER);
				days[j].setForeground((((j+1))==currentDay ? Color.RED : Color.red));
                                if((j+1)==currentDay)
                                    days[j].setBorder(BorderFactory.createLineBorder(Color.blue, 1));
                                days[j].setFont(new Font("Arial", Font.BOLD, 12));
				days[j].setToolTipText((((j+1))==currentDay ? "Today's date is: " : "The date is: ") + (j+1) + ", " + monthOfYear[months -1] + ", " + year);
				x += 31;
				
				if(i%7 == 0)
				{
					y += 31;
					x = 10;
				}
				
				jPanel3.add(days[j]);
			}
		
		}
		repaint();
		revalidate();
	}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }
    private javax.swing.JButton left,right;
    String [] dayWeek = {"SUN","MON","TUE","WED","THU","FRI","SAT"};
    String [] monthOfYear = {"January", "February", "March","April","May","June","July","August","September","Octomber","November","December"};
    String [] weekDays = {"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"};
    int year,month,day;
    JLabel [] days , daysOfWeek;
    JLabel bg, todayDate, monthYear;
    GregorianCalendar calendar;
    String [] images = {"/hostel/management/system/back.jpg","/hostel/management/system/inner.jpg","/hostel/management/system/hall.jpg"};


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JPanel container;
    private javax.swing.JLabel home;
    private javax.swing.JLabel hostel;
    private javax.swing.JLabel hostel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel pix;
    private javax.swing.JLabel record;
    private javax.swing.JLabel record1;
    private javax.swing.JLabel room;
    private javax.swing.JLabel room1;
    private javax.swing.JLabel student;
    private javax.swing.JLabel student1;
    // End of variables declaration//GEN-END:variables
}
