/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hostel.management.system;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.BorderFactory;

/**
 *
 * @author HP
 */
public class Record extends javax.swing.JPanel {

    /**
     * Creates new form Record
     */
    public Record() {
        initComponents();
        setRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();
        sn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        search = new javax.swing.JComboBox();
        input = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENTS RECORD");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Records", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(204, 51, 0))); // NOI18N

        container.setLayout(new java.awt.GridBagLayout());

        sn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        sn.setForeground(new java.awt.Color(255, 102, 0));
        sn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sn.setText("S/N");
        sn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        sn.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(sn, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STUDENT ID");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ROOM ID");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATE CHECKED IN");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RENT DUE-DATE");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DROP");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        container.add(jLabel6, gridBagConstraints);

        jScrollPane2.setViewportView(container);

        search.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ", "Student Id.", "Room id." }));

        input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputkeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputkeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputkeyTyped
        // TODO add your handling code here:
        if(!(input.getText().equals("") || search.getSelectedIndex() == 0))
        {
            String query = (search.getSelectedIndex() == 1 ? "student_id" : "room_id");

            try {
                cont = new GridBagConstraints();
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel", "root", "");
                st = con.createStatement();
                String query1 = "SELECT * FROM room_alloc WHERE "+ query + " LIKE '" + input.getText() + "%'";
                rs = st.executeQuery(query1);

                int i=1;
                container.removeAll();
                setTitle();

                while(rs.next())
                {
                    JLabel sn = new JLabel("" + i);
                    sn.setPreferredSize(new Dimension(50,25));
                    sn.setHorizontalAlignment(SwingConstants.CENTER);
                    sn.setForeground(Color.red);
                    sn.setFont(new Font("Dialog", Font.BOLD, 12));
                    addComp(sn, 0, i);

                    JLabel std = new JLabel(rs.getString(1));
                    std.setHorizontalAlignment(SwingConstants.CENTER);
                    std.setForeground(Color.BLACK);
                    std.setFont(new Font("Dialog", Font.BOLD, 12));
                    std.setName(rs.getString(1));
                    std.setToolTipText("Click to view student Record");
                    std.addMouseListener(new MouseAdapter() {
                        @Override
                        public void mouseEntered(MouseEvent evt)
                        {
                            std.setForeground(Color.RED);
                        }
                        @Override
                        public void mouseExited(MouseEvent evt)
                        {
                            std.setForeground(Color.BLACK);
                        }
                        @Override
                        public void mouseClicked(MouseEvent evt)
                        {
                            displayProfile(evt);
                        }
                    });
                    addComp(std, 1,i);

                    JLabel rmn = new JLabel(rs.getString(2));
                    rmn.setHorizontalAlignment(SwingConstants.CENTER);
                    rmn.setForeground(Color.BLACK);
                    rmn.setFont(new Font("Dialog", Font.BOLD, 12));
                    addComp(rmn, 2,i);

                    JLabel in = new JLabel(rs.getString(3));
                    in.setHorizontalAlignment(SwingConstants.CENTER);
                    in.setForeground(Color.BLACK);
                    in.setFont(new Font("Dialog", Font.BOLD, 12));
                    addComp(in, 3,i);

                    JLabel out = new JLabel(rs.getString(4));
                    out.setHorizontalAlignment(SwingConstants.CENTER);
                    out.setForeground(Color.BLACK);
                    out.setFont(new Font("Dialog", Font.BOLD, 12));
                    addComp(out, 4,i);
                    
                    JButton drop = new JButton(new ImageIcon(getClass().getResource("cancel.png")));
                    drop.setActionCommand(rs.getString(1));
                    drop.addActionListener(this::setDrop);
                    addComp(drop, 5, i++);
                }
                container.repaint();
                container.revalidate();
                container.validate();
            }
            catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
        else
            setRecord();
    }//GEN-LAST:event_inputkeyTyped

    private void setRecord()
    {
        try {
            cont = new GridBagConstraints();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hostel", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM room_alloc");
            
            int i=1;
            container.removeAll();
            setTitle();
            
            while(rs.next())
            {
                JLabel sn = new JLabel("" + i);
                sn.setPreferredSize(new Dimension(50,25));
                sn.setHorizontalAlignment(SwingConstants.CENTER);
                sn.setForeground(Color.red);
                sn.setFont(new Font("Dialog", Font.BOLD, 12));
                addComp(sn, 0, i);
                
                JLabel std = new JLabel(rs.getString(1));
                std.setHorizontalAlignment(SwingConstants.CENTER);
                std.setForeground(Color.BLACK);
                std.setFont(new Font("Dialog", Font.BOLD, 12));
                std.setName(rs.getString(1));
                std.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseEntered(MouseEvent evt)
                    {
                        std.setForeground(Color.RED);
                    }
                    @Override
                    public void mouseExited(MouseEvent evt)
                    {
                        std.setForeground(Color.BLACK);
                    }
                    @Override
                    public void mouseClicked(MouseEvent evt)
                    {
                        displayProfile(evt);
                    }
});
                addComp(std, 1,i);
                
                JLabel rmn = new JLabel(rs.getString(2));
                rmn.setHorizontalAlignment(SwingConstants.CENTER);
                rmn.setForeground(Color.BLACK);
                rmn.setFont(new Font("Dialog", Font.BOLD, 12));
                addComp(rmn, 2,i);
                
                JLabel in = new JLabel(rs.getString(3));
                in.setHorizontalAlignment(SwingConstants.CENTER);
                in.setForeground(Color.BLACK);
                in.setFont(new Font("Dialog", Font.BOLD, 12));
                addComp(in, 3,i);
                
                JLabel out = new JLabel(rs.getString(4));
                out.setHorizontalAlignment(SwingConstants.CENTER);
                out.setForeground(Color.BLACK);
                out.setFont(new Font("Dialog", Font.BOLD, 12));
                addComp(out, 4,i);
                
                JButton drop = new JButton(new ImageIcon(getClass().getResource("cancel.png")));
                drop.setActionCommand(rs.getString(1));
                drop.addActionListener(this::setDrop);
                addComp(drop, 5, i++);
            }
            container.repaint();
            container.revalidate();
            container.validate();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    private void displayProfile(MouseEvent evt)
    {
        new Profile(evt.getComponent().getName(),null, true).setVisible(true);
        //System.out.println(evt.getComponent().getName());
    }
    private void setDrop(ActionEvent evt)
    {
        int a = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete "+ evt.getActionCommand() + " from record", "Drop Record", JOptionPane.YES_NO_OPTION);
        
        if(a == JOptionPane.YES_OPTION)
        {
            try {
                //drop record from db
                ps = con.prepareStatement("DELETE FROM room_alloc WHERE student_id='" + evt.getActionCommand() + "'");
                int b = ps.executeUpdate();
                
                ps = con.prepareStatement("UPDATE rooms SET status = 'available'");
                int c = ps.executeUpdate();
                
                if(b != -1 && c != -1)
                {
                    JOptionPane.showMessageDialog(this, evt.getActionCommand() + " Succesfully deleted from Record");
                    setRecord();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Operation failed");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Record.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void addComp(JComponent comp, int x, int y)
    {
        cont.anchor = GridBagConstraints.PAGE_START;
        cont.fill = GridBagConstraints.BOTH;
        cont.gridheight = 1;
        cont.gridwidth = 1;
        cont.gridx = x;
        cont.gridy = y;
        
        comp.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        container.add(comp, cont);
    }
    private void setTitle()
    {
        JLabel sn = new JLabel("S/N");
        sn.setPreferredSize(new Dimension(50,25));
        sn.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        sn.setFont(new Font("Dialog", Font.BOLD, 12));
        sn.setForeground(new Color(255,102,0));
        sn.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(sn, 0,0);
        
        JLabel std = new JLabel("STUDENT ID");
        std.setPreferredSize(new Dimension(120,25));
        std.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        std.setFont(new Font("Dialog", Font.BOLD, 12));
        std.setForeground(new Color(255,102,0));
        std.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(std, 1,0);
        
        JLabel rm = new JLabel("ROOM ID");
        rm.setPreferredSize(new Dimension(120,25));
        rm.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        rm.setFont(new Font("Dialog", Font.BOLD, 12));
        rm.setForeground(new Color(255,102,0));
        rm.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(rm , 2,0);
        
        JLabel in = new JLabel("DATE CHECKED IN");
        in.setPreferredSize(new Dimension(150,25));
        in.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        in.setFont(new Font("Dialog", Font.BOLD, 12));
        in.setForeground(new Color(255,102,0));
        in.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(in, 3,0);
        
        JLabel out = new JLabel("RENT DUE DATE");
        out.setPreferredSize(new Dimension(150,25));
        out.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        out.setFont(new Font("Dialog", Font.BOLD, 12));
        out.setForeground(new Color(255,102,0));
        out.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(out, 4, 0);
        
        JLabel drop = new JLabel("DROP");
        drop.setPreferredSize(new Dimension(50,25));
        drop.setBorder(BorderFactory.createLineBorder(new Color(0,0,204), 1));
        drop.setFont(new Font("Dialog", Font.BOLD, 12));
        drop.setForeground(new Color(255,102,0));
        drop.setHorizontalAlignment(SwingConstants.CENTER);
        addComp(drop, 5, 0);
    }

    private GridBagConstraints cont;
    private Connection con;
    private Statement st;
    private ResultSet rs;
    private PreparedStatement ps;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox search;
    private javax.swing.JLabel sn;
    // End of variables declaration//GEN-END:variables
}
